### ISSUE TITLE
Missing ) after argument list in _layout.ejs

### ISSUE THREAD

**Issue by benpetersen** [cardeo/booterator#1]
When I add your suggested _layout.ejs raw text to the file and compile, I get a error stating

"missing ) after argument list in ...\_layout.ejs while compiling ejs"

Below is the full output 
{
  "source": "EJS",
  "dest": "HTML",
  "filename": "C:\Users\Ben\Documents\Bens Projects\my-blog\_layout.ejs",
  "lineno": null,
  "name": "SyntaxError",
  "message": "missing ) after argument list in C:\Users\Ben\Documents\Bens Projects\my-blog\_layout.ejs while compiling ejs",
  "stack": "<!DOCTYPE html> \r\n<html lang=\"en\">\r\n<head>\r\n  <meta charset=\"utf-8\">\r\n  <title><%- pageTitle %> | <%- siteTitle %></title>\r\n  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/theme.css\">\r\n</head>\r\n<body>\r\n  <%- partial(\"partial/_header\") %>\r\n   \r\n  <%- yield %>\r\n\r\n  <%- partial(partial/_footer\") %>\r\n\r\n  \r\n  <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n  <script src=\"js/project.js\" type=\"text/javascript\"></script>\r\n</body>\r\n</html>"
}

**Comment by cardeo** [comment]
kinda hard to tell from this, need the source of your layout file. There will be a syntax error in there somewhere

**Comment by benpetersen** [comment]
<!DOCTYPE html> 
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%- pageTitle %> | <%- siteTitle %></title>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="css/theme.css">
</head>
<body>
  <%- partial("partial/_header") %>
   
  <%- yield %>

  <%- partial(partial/_footer") %>

  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="js/project.js" type="text/javascript"></script>
</body>
</html>

**Comment by benpetersen** [comment]
Here's [my repo](https://github.com/benpetersen/ben-petersen-blog/blob/master/_layout.ejs)

**Comment by benpetersen** [comment]
Found my issue on the partial(partial/_footer") line, please close this ticket

**Comment by cardeo** [comment]
Ok cool
